---
title: "HW6"
author: "Duzhi Zhao"
date: "11/18/2019"
output: github_document
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
library(tidyverse)
library(viridis)

knitr::opts_chunk$set(
  echo = TRUE,
  warning = FALSE,
  message = FALSE,
  fig.width = 8, 
  fig.height = 6,
  out.width = "100%"
)
options(
  ggplot2.continuous.colour = "viridis",
  ggplot2.continuous.fill = "viridis"
)
scale_colour_discrete = scale_colour_viridis_d
scale_fill_discrete = scale_fill_viridis_d
theme_set(theme_minimal() + theme(legend.position = "bottom"))
```

# Problem 1
```{r}
# Import and tidy dataset
birth_w = read.csv("./data/birthweight.csv") %>% 
  janitor::clean_names() %>% 
  # Change variable type from numeric to ordered factor
  mutate(
    babysex = ordered(babysex, levels = c(1, 2)),
    frace = ordered(frace, levels = c(1, 2, 3, 4, 8)),
    malform = ordered(malform, levels = c(0, 1)),
    mrace = ordered(mrace, levels = c(1, 2, 3, 4))
  ) %>% 
  # Recode variables with direct information
  mutate(
    babysex = recode(babysex, 
                     `1` = "male",
                     `2` = "female"),
    frace = recode(frace, 
                   `1` = "White",
                   `2` = "Black",
                   `3` = "Asian",
                   `4` = "Puerto Rican",
                   `8` = "Other"),
    malform = recode(malform, 
                     `0` = "absent",
                     `1` = "present"),
    mrace = recode(mrace,
                   `1` = "White",
                   `2` = "Black",
                   `3` = "Asian",
                   `4` = "Puerto Rican")
  )

# Check missing value
summary(is.na(birth_w)) # all have FALSE: 4342 --> NO MISSING VALUE
```

```{r}
# Check normality of bwt data
birth_w %>% 
  ggplot(aes(x = bwt)) +
  geom_histogram(bins = 50) +
  labs(x = "Birthweight (g)",
       y = "Count",
       title = "Normality Check on birthweight")

# MLR - 'smoken' and 'momage' as predictors
fit = lm(bwt ~ smoken + momage, data = birth_w)
summary(fit)
```

```{r}
fit %>% 
  broom::tidy() %>% 
  mutate(term = str_replace(term, "^smoken", "No. of cigarettes smoked per day")) %>%
  mutate(term = str_replace(term, "^momage", "Mother's age at delivery")) %>% 
  knitr::kable(digits = 3)
```

```{r}
# Add residuals and predictions (fitted values) into dataset 'birth_w'
bwt_resid_pred = 
  birth_w %>% 
  modelr::add_residuals(fit) %>% 
  modelr::add_predictions(fit)

# Plot: Residual vs. Fitted value 
bwt_resid_pred %>% 
  ggplot(aes(x = pred, y = resid)) +
  geom_point(alpha = 0.4) + 
  geom_abline(intercept = 0, slope = 0, color = "red") +
  labs(x = "Predicted/Fitted value",
      y = "Residual",
      title = "Residual vs. Fitted value")
```

